//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductPage.Admin
{
    public partial class Dashboard
    {
        /// <summary>lblTotalSales control.</summary>
        protected global::System.Web.UI.WebControls.Label lblTotalSales;

        /// <summary>lblTotalOrders control.</summary>
        protected global::System.Web.UI.WebControls.Label lblTotalOrders;

        /// <summary>lblTotalCustomers control.</summary>
        protected global::System.Web.UI.WebControls.Label lblTotalCustomers;

        /// <summary>ddlCategory — filter dropdown populated from Categories table.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;

        /// <summary>txtDateFrom — date range start filter.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtDateFrom;

        /// <summary>txtDateTo — date range end filter.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtDateTo;

        /// <summary>btnApply — applies selected filters.</summary>
        protected global::System.Web.UI.WebControls.Button btnApply;

        /// <summary>btnReset — clears all filters.</summary>
        protected global::System.Web.UI.WebControls.Button btnReset;

        /// <summary>SqlDataSource1 control.</summary>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource1;

        /// <summary>gvRecent GridView control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvRecent;
    }
}
