//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductPage
{
    public partial class PurchaseHistory
    {
        protected global::System.Web.UI.WebControls.Label lblTotalOrders;
        protected global::System.Web.UI.WebControls.Label lblTotalItems;
        protected global::System.Web.UI.WebControls.Label lblTotalSpent;
        protected global::System.Web.UI.WebControls.Panel pnlOrders;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
    }
}
